// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzGpTtX5oLM_8FH0kMNNQ47cDU8Q5StEY',
    appId: '1:650935630603:web:f3c63c464d42bde49b800e',
    messagingSenderId: '650935630603',
    projectId: 'flutter-project-e-commerce',
    authDomain: 'flutter-project-e-commerce.firebaseapp.com',
    storageBucket: 'flutter-project-e-commerce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe0DkvUQ8vX724qhJhr4Ko84E2H0hk_uQ',
    appId: '1:650935630603:android:b84d2bf79cea457e9b800e',
    messagingSenderId: '650935630603',
    projectId: 'flutter-project-e-commerce',
    storageBucket: 'flutter-project-e-commerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1tY5lj0chmyN20SOCpM03w-wqK6z3SMM',
    appId: '1:650935630603:ios:85a16acec842c2039b800e',
    messagingSenderId: '650935630603',
    projectId: 'flutter-project-e-commerce',
    storageBucket: 'flutter-project-e-commerce.appspot.com',
    androidClientId: '650935630603-2e8hcapt2hdi7tgsqvdiip4ofo65qkd0.apps.googleusercontent.com',
    iosClientId: '650935630603-hthm2p69gqbso6ob95rig9tu8r0en374.apps.googleusercontent.com',
    iosBundleId: 'com.abhishekthankachan.glimp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1tY5lj0chmyN20SOCpM03w-wqK6z3SMM',
    appId: '1:650935630603:ios:79dc7cdba748c15e9b800e',
    messagingSenderId: '650935630603',
    projectId: 'flutter-project-e-commerce',
    storageBucket: 'flutter-project-e-commerce.appspot.com',
    androidClientId: '650935630603-2e8hcapt2hdi7tgsqvdiip4ofo65qkd0.apps.googleusercontent.com',
    iosClientId: '650935630603-usqs3e673oh8q111nvs5eg00ia2mtrrh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
